config/routes.rb
Rails.application.routes.draw do
  post '/rate' => 'rater#create', :as => 'rate'
  get 'aboutus/index'
  resources :reviews
  resources :orders do
    resources :reviews
  end
  resources :products
  resources :categories
  devise_for :users
  resources :charges
  root to: 'home#index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/address.rb
class Address < ApplicationRecord
end

app/models/average_cache.rb
class AverageCache < ActiveRecord::Base
  belongs_to :rater, :class_name => "User"
  belongs_to :rateable, :polymorphic => true
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :products
end

app/models/feedback.rb
class Feedback < ApplicationRecord
  mount_uploader :image, ImageUploader

  def blank_stars
    return 5 - rating.to_i
  end
end

app/models/order.rb
class Order < ApplicationRecord
  ratyrate_rateable "taste", "price"

  before_save do
    self.vegetable.gsub!(/[\[\]\"]/, "") if attribute_present?("vegetable")
  end

end

app/models/overall_average.rb
class OverallAverage < ActiveRecord::Base
  belongs_to :rateable, :polymorphic => true
end

app/models/payment.rb
class Payment < ApplicationRecord
end

app/models/person.rb
class Person < ApplicationRecord
  validates :email, format: { with: URI::MailTo::EMAIL_REGEXP }
  validates :phone, format: { with: /\A[+-]?\d+\z/, message: "contains alphabet. Insert only number please!!!." }, length: {minimum: 8}
  validates :password, length: {minimum: 6}
end

app/models/product.rb
class Product < ApplicationRecord
  belongs_to :category
end

app/models/rate.rb
class Rate < ActiveRecord::Base
  belongs_to :rater, :class_name => "User"
  belongs_to :rateable, :polymorphic => true

  #attr_accessible :rate, :dimension

end

app/models/rating_cache.rb
class RatingCache < ActiveRecord::Base
  belongs_to :cacheable, :polymorphic => true
end

app/models/review.rb
class Review < ApplicationRecord
  mount_uploader :image, ImageUploader
end

app/models/user.rb
class User < ApplicationRecord
  ratyrate_rater
  has_many :orders
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  before_action :set_order, only: [:show, :edit, :update, :destroy]

  # GET /orders
  # GET /orders.json
  def index
    @orders = Order.all
  end

  # GET /orders/1
  # GET /orders/1.json
  def show
  end

  # GET /orders/new
  def new
    @order = Order.new
  end

  # GET /orders/1/edit
  def edit
  end

  # POST /orders
  # POST /orders.json
  def create
    @order = Order.new(order_params)

    respond_to do |format|
      if @order.save
        format.html { redirect_to @order, notice: 'Order was successfully created.' }
        format.json { render :show, status: :created, location: @order }
      else
        format.html { render :new }
        format.json { render json: @order.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /orders/1
  # PATCH/PUT /orders/1.json
  def update
    respond_to do |format|
      if @order.update(order_params)
        format.html { redirect_to @order, notice: 'Order was successfully updated.' }
        format.json { render :show, status: :ok, location: @order }
      else
        format.html { render :edit }
        format.json { render json: @order.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /orders/1
  # DELETE /orders/1.json
  def destroy
    @order.destroy
    respond_to do |format|
      format.html { redirect_to orders_url, notice: 'Order was successfully destroyed.' }
      format.json { head :no_content }
    end
  end


  private
    # Use callbacks to share common setup or constraints between actions.
    def set_order
      @order = Order.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def order_params
      params.require(:order).permit(:breadtype, :ingredient, :condiment, :amount, vegetable:[])
    end
end

app/helpers/aboutus_helper.rb
module AboutusHelper
end

app/helpers/addresses_helper.rb
module AddressesHelper
end

app/helpers/charges_helper.rb
module ChargesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
  def checked(area)
    @order.vegetable.nil? ? false :  @order.vegetable.match(area)
  end
end

app/helpers/payments_helper.rb
module PaymentsHelper
end

app/helpers/people_helper.rb
module PeopleHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/orders/_form.html.erb
<%= form_with(model: order, local: true) do |form| %>
  <% if order.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(order.errors.count, "error") %> prohibited this order from being saved:</h2>

      <ul>
      <% order.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :breadtype %>
    <%= form.select :breadtype, ['White bread', 'Wholemeal bread', 'Rye bread']%>
  </div>

  <div class="field">
    <%= form.label :ingredient %>
    <%= form.select :ingredient, ['None', 'Ham', 'Bacon', 'Chicken', 'Salami', 'Quinoa']%>
  </div>

  <div class="field">
    <%= form.label :vegetable %>

    <%= label_tag 'tomato', 'Tomato' %>
    <%= check_box_tag 'order[vegetable][]', 'Tomato', id:'tomato' %>

    <%= label_tag 'lettuce', 'Lettuce' %>
    <%= check_box_tag 'order[vegetable][]', 'Lettuce', id:'lettuce' %>

    <%= label_tag 'onions', 'Onions' %>
    <%= check_box_tag 'order[vegetable][]', 'Onions', id:'onions' %>

    <%= label_tag 'cucumber', 'Cucumber' %>
    <%= check_box_tag 'order[vegetable][]', 'Cucumber', id:'cucumbers' %>

  </div>

  <div class="field">
    <%= form.label :condiment %>
    <%= form.select :condiment, ['None', 'Mayonnaise', 'Ketchup', 'Curry', 'Chilli', 'Sour cream']%>
  </div>

  <div class="field">
    <%= form.label :amount %>
    <%= form.number_field :amount, min:"1", value:"1" %>
  </div>

  <div class="field">
    <%= label_tag 'delivery', 'Delivery' %>
    <%= check_box_tag 'order[delivery]', 'Delivery', id:'delivery' %>
  </div>


  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/orders/edit.html.erb
<h1>Editing Order</h1>

<%= render 'form', order: @order %>

<%= link_to 'Show', @order %> |
<%= link_to 'Back', orders_path %>

app/views/orders/index.html.erb
<html>
<head>
  <meta charset="utf-8">
  <title> Hoagie Online Shop </title>
</head>
<body>
<header>
  <section>
    <h1> Your Orders </h1>

    <% if current_user %>
      <h4>Hello <%= current_user.name %>!</h4>
    <% end %>
  </section>
  <nav>
    <ul>
      <% if current_user %>
        <li><%= link_to 'Home', root_path %></li>

        <li><%= link_to 'Products', products_path %></li>

        <li><%= link_to 'Your Orders', orders_path, class: "active" %></li>

        <li><%= link_to 'Change Personal Details', edit_user_registration_path %></li>

        <li><%= link_to 'Reviews', reviews_path %></li>

        <li><%= link_to 'About Us', aboutus_index_path %></li>

        <li><%= link_to 'Sign out', destroy_user_session_path, method: :delete %></li>


      <% else %>
        <li><%= link_to 'Home', root_path, class: "active" %></li>

        <li><%= link_to 'Products', products_path %></li>

        <li><%= link_to 'Reviews', reviews_path %></li>

        <li><%= link_to 'About Us', aboutus_index_path %></li>

        <li><%= link_to 'Products', products_path %></li>

        <li><%= link_to 'Sign up', new_user_registration_path %></li>

        <li><%= link_to 'Sign in', new_user_session_path %></li>
      <% end %>

    </ul>
  </nav>
  <hr>
</header>
<main>
  <figure>
    <%= image_tag("order", height: '290', width: '580', class: "bild") %>
  </figure>
  <section>

    <% if current_user.admin %>
      <table align="center">
        <thead>
        <div class="row">
          <div class="col-sm-2"><span class="label label-primary">Breadtype</span></div>
          <div class="col-sm-2"><span class="label label-warning">Ingredient</span></div>
          <div class="col-sm-2"><span class="label label-success">Vegetable</span></div>
          <div class="col-sm-2"><span class="label label-danger">Condiment</span></div>
          <div class="col-sm-1"><span class="label label-default">Amout</span></div>
          <div class="col-sm-3"></div>
        </div>
        </thead>

        <tbody>
        <% @orders.each do |order| %>
          <div class="row">
            <div class="col-sm-2"><%= order.breadtype %></div>
            <div class="col-sm-2"><%= order.ingredient %></div>
            <div class="col-sm-2"><%= order.vegetable %></div>
            <div class="col-sm-2"><%= order.condiment %></div>
            <div class="col-sm-1"><%= order.amount %></div>
            <div class="col-sm-3">
              <%= link_to 'Show', order %> |
              <%= link_to 'Modify', edit_order_path(order) %> |
              <%= link_to 'Cancel', order, method: :delete, data: {confirm: 'Are you sure?'} %></div>
          </div>
          </div>
        <% end %>
        </tbody>
      </table>

    <% else %>

      <table align="center">
        <thead>
        <div class="row">
          <div class="col-sm-2"><span class="label label-primary">Breadtype</span></div>
          <div class="col-sm-2"><span class="label label-warning">Ingredient</span></div>
          <div class="col-sm-2"><span class="label label-success">Vegetable</span></div>
          <div class="col-sm-2"><span class="label label-danger">Condiment</span></div>
          <div class="col-sm-1"><span class="label label-default">Amout</span></div>
          <div class="col-sm-3"></div>
        </div>
        </thead>

        <tbody>
        <% @orders.each do |order| %>
          <div class="row">
            <div class="col-sm-2"><%= order.breadtype %></div>
            <div class="col-sm-2"><%= order.ingredient %></div>
            <div class="col-sm-2"><%= order.vegetable %></div>
            <div class="col-sm-2"><%= order.condiment %></div>
            <div class="col-sm-1"><%= order.amount %></div>
            <div class="col-sm-3">
              <%= link_to 'Show', order %> |
              <%= link_to 'Modify', edit_order_path(order) %>
             </div>
          </div>
          </div>
        <% end %>
        </tbody>
      </table>

    <% end %>

    <br>

    <%= link_to 'Make an order', new_order_path, class: "btn btn-primary btn-lg btn-block", role: "button" %>
  </section>
  <hr>
</main>
<footer>
  <h3> You will find us here: </h3>
  <div>
    <a href="https://www.facebook.com/" target="blank1"><%= image_tag("facebook", :size => "40x40") %></a>
    <a href="https://instagram.com/" target="blank2"><%= image_tag("instagram", :size => "40x40") %></a>
    <a href="https://www.twitter.com/" target="blank3"><%= image_tag("twitter", :size => "40x40") %></a>
    <div>
</footer>
</body>
</html>

app/views/orders/new.html.erb
<h1>New Order</h1>

<%= render 'form', order: @order %>

<%= link_to 'Back', orders_path %>

app/views/orders/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Breadtype:</strong>
  <%= @order.breadtype %>
</p>

<p>
  <strong>Ingredient:</strong>
  <%= @order.ingredient %>
</p>

<p>
  <strong>Vegetable:</strong>
  <%= @order.vegetable %>
</p>

<p>
  <strong>Condiment:</strong>
  <%= @order.condiment %>
</p>

<p>
  <strong>Amount:</strong>
  <%= @order.amount %>
</p>

<p>
  <strong>Total Price:</strong>
  <%= @order.price = @order.amount*3  %>  €
</p>

<%= form_tag charges_path do %>
  <article>
    <% if flash[:error].present? %>
      <div id="error_explanation">
        <p><%= flash[:error] %></p>
      </div>
    <% end %>
  </article>

  <script src="https://checkout.stripe.com/checkout.js" class="stripe-button"
          data-key="<%= Rails.configuration.stripe[:publishable_key] %>"
          data-description="Hoagie Order"
          data-locale="auto"
          data-currency="EUR"
          data-shipping-address="true"></script>
<% end %>

<!--<%#= link_to 'Edit', edit_order_path(@order) %> |-->
<%= link_to 'Back', orders_path %>