config/routes.rb
Rails.application.routes.draw do
  post '/rate' => 'rater#create', :as => 'rate'
  get 'aboutus/index'
  resources :reviews
  resources :orders do
    resources :reviews
  end
  resources :products
  resources :categories
  devise_for :users
  resources :charges
  root to: 'home#index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/address.rb
class Address < ApplicationRecord
end

app/models/average_cache.rb
class AverageCache < ActiveRecord::Base
  belongs_to :rater, :class_name => "User"
  belongs_to :rateable, :polymorphic => true
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :products
end

app/models/feedback.rb
class Feedback < ApplicationRecord
  mount_uploader :image, ImageUploader

  def blank_stars
    return 5 - rating.to_i
  end
end

app/models/order.rb
class Order < ApplicationRecord
  ratyrate_rateable "taste", "price"

  before_save do
    self.vegetable.gsub!(/[\[\]\"]/, "") if attribute_present?("vegetable")
  end

end

app/models/overall_average.rb
class OverallAverage < ActiveRecord::Base
  belongs_to :rateable, :polymorphic => true
end

app/models/payment.rb
class Payment < ApplicationRecord
end

app/models/person.rb
class Person < ApplicationRecord
  validates :email, format: { with: URI::MailTo::EMAIL_REGEXP }
  validates :phone, format: { with: /\A[+-]?\d+\z/, message: "contains alphabet. Insert only number please!!!." }, length: {minimum: 8}
  validates :password, length: {minimum: 6}
end

app/models/product.rb
class Product < ApplicationRecord
  belongs_to :category
end

app/models/rate.rb
class Rate < ActiveRecord::Base
  belongs_to :rater, :class_name => "User"
  belongs_to :rateable, :polymorphic => true

  #attr_accessible :rate, :dimension

end

app/models/rating_cache.rb
class RatingCache < ActiveRecord::Base
  belongs_to :cacheable, :polymorphic => true
end

app/models/review.rb
class Review < ApplicationRecord
  mount_uploader :image, ImageUploader
end

app/models/user.rb
class User < ApplicationRecord
  ratyrate_rater
  has_many :orders
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: [:show, :edit, :update, :destroy]

  # GET /products
  # GET /products.json
  def index
    @products = Product.all
  end

  # GET /products/1
  # GET /products/1.json
  def show
  end

  # GET /products/new
  def new 
    @product = Product.new 
    @categories = Category.all.map{ |c| [ c.name, c.id ] }
  end

  # GET /products/1/edit
  def edit
    @categories = Category.all.map{|c| [ c.name, c.id ] }
  end

  # POST /products
  # POST /products.json
  def create
    @product = Product.new(product_params)
    @product.category_id = params[:category_id] 

    respond_to do |format|
      if @product.save
        format.html { redirect_to @product, notice: 'Product was successfully created.' }
        format.json { render :show, status: :created, location: @product }
      else
        format.html { render :new }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1
  # PATCH/PUT /products/1.json
  def update
    respond_to do |format|
      @product.category_id = params[:category_id]
      if @product.update(product_params)
        format.html { redirect_to @product, notice: 'Product was successfully updated.' }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1
  # DELETE /products/1.json
  def destroy
    @product.destroy
    respond_to do |format|
      format.html { redirect_to products_url, notice: 'Product was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def product_params
      params.require(:product).permit(:name, :vegan, :category_id, :desc)
    end
end

app/helpers/aboutus_helper.rb
module AboutusHelper
end

app/helpers/addresses_helper.rb
module AddressesHelper
end

app/helpers/charges_helper.rb
module ChargesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
  def checked(area)
    @order.vegetable.nil? ? false :  @order.vegetable.match(area)
  end
end

app/helpers/payments_helper.rb
module PaymentsHelper
end

app/helpers/people_helper.rb
module PeopleHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/products/_form.html.erb
<%= form_with(model: product, local: true) do |form| %>
  <% if product.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(product.errors.count, "error") %> prohibited this product from being saved:</h2>

      <ul>
      <% product.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :desc %>
    <%= form.text_area :desc %>
  </div>

  <div class="field">
    <%= form.label :vegan %>
    <%= form.check_box :vegan %>
  </div>

  <div class="field">
    <%= form.label :category_id %>
    <%= select_tag "category_id", options_for_select(@categories), prompt: "Select one" %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/products/edit.html.erb
<h1>Editing Product</h1>

<%= render 'form', product: @product %>

<%= link_to 'Show', @product %> |
<%= link_to 'Back', products_path %>

app/views/products/index.html.erb
<html>
  <head>
    <meta charset="utf-8">
    <title> Hoagie Online Shop </title>
  </head>
  <body>
    <header>
      <section>
        <h1> Our Products</h1>
        <% if current_user %>
          <h4>Hello <%= current_user.name %>!</h4>
        <% end %>
      </section>  
      <nav>
        <ul>
          <% if current_user %>
    <li><%= link_to 'Home', root_path %></li>

    <li><%= link_to 'Products', products_path, class: "active" %></li>

    <li><%= link_to 'Your Orders', orders_path %></li>

    <li><%= link_to 'Change Personal Details',edit_user_registration_path %></li>

    <li><%= link_to 'Reviews', reviews_path %></li> 

    <li><%= link_to 'About Us', aboutus_index_path %></li>

    <li><%= link_to 'Sign out', destroy_user_session_path, method: :delete %></li>

  

<% else %>
    <li><%= link_to 'Home', root_path %></li>

    <li><%= link_to 'Products', products_path, class: "active" %></li>

    <li><%= link_to 'Reviews', reviews_path %></li> 

    <li><%= link_to 'About Us', aboutus_index_path %></li> 

    <li><%= link_to 'Sign up', new_user_registration_path %></li>

    <li><%= link_to 'Sign in', new_user_session_path %></li>
<% end %>

        </ul>
      </nav>
      <hr>
    </header>

    <main>
      <section>
          <%= image_tag("ingredients.jpg", height: '290', width: '800', class: "bild") %>

  <thead>
    <div class="row">
  <div class="col-sm-2"><span class="label label-primary">Name</span></div>
  <div class="col-sm-1"><span class="label label-success">Vegan</span></div>
  <div class="col-sm-4"><span class="label label-warning">Description</span></div>
  <div class="col-sm-3"><span class="label label-default">Category</span></div>
  <% if current_user && current_user.admin %>
    <div class="col-sm-2"></div>
  <% end %>
</div>
  </thead>

  <tbody>
    <% @products.each do |product| %>

<div class="row">
  <div class="col-sm-2"><%= product.name %></div>
  <div class="col-sm-1"><% if product.vegan %>
            <span class="glyphicon glyphicon-ok"></span>
          <% else %>
            <span class="glyphicon glyphicon-remove"></span>
          <% end %></div>
  <div class="col-sm-4"><%= product.desc %></div>
  <div class="col-sm-3"><%= link_to Category.find(product.category_id).name, category_path(product.category_id) %></div>
  <% if current_user && current_user.admin %>
    <div class="col-sm-2"><td><%= link_to 'Show', product %></td>
            <td><%= link_to 'Edit', edit_product_path(product) %></td>
            <td><%= link_to 'Destroy', product, method: :delete, data: { confirm: 'Are you sure?' } %></td>
          </div>
  <% end %>
</div>

        

    <% end %>
  </tbody>

<br>

<% if current_user && current_user.admin %>
  <%= link_to 'New Product', new_product_path %>
<% end %>
</section>
</main>
    <footer> 
      <h3> You will find us here: </h3>
       <div>
        <a href="https://www.facebook.com/" target="blank1"><%= image_tag("facebook", :size => "40x40") %></a>
        <a href="https://instagram.com/" target="blank2"><%= image_tag("instagram", :size => "40x40") %></a>
        <a href="https://www.twitter.com/" target="blank3"><%= image_tag("twitter", :size => "40x40") %></a>
       <div>
    </footer>
  </body> 
</html>

app/views/products/new.html.erb
<h1>New Product</h1>

<%= render 'form', product: @product %>

<%= link_to 'Back', products_path %>

app/views/products/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @product.name %>
</p>

<p>
  <strong>Vegan:</strong>
  <%= @product.vegan %>
</p>

<p>
  <strong>Description:</strong>
  <%= @product.desc %>
</p>

<p>
  <strong>Category:</strong>
  <%= link_to Category.find(@product.category_id).name, category_path(@product.category_id) %>
</p>

<%= link_to 'Edit', edit_product_path(@product) %> |
<%= link_to 'Back', products_path %>