config/routes.rb
Rails.application.routes.draw do
  post '/rate' => 'rater#create', :as => 'rate'
  get 'aboutus/index'
  resources :reviews
  resources :orders do
    resources :reviews
  end
  resources :products
  resources :categories
  devise_for :users
  resources :charges
  root to: 'home#index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/address.rb
class Address < ApplicationRecord
end

app/models/average_cache.rb
class AverageCache < ActiveRecord::Base
  belongs_to :rater, :class_name => "User"
  belongs_to :rateable, :polymorphic => true
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :products
end

app/models/feedback.rb
class Feedback < ApplicationRecord
  mount_uploader :image, ImageUploader

  def blank_stars
    return 5 - rating.to_i
  end
end

app/models/order.rb
class Order < ApplicationRecord
  ratyrate_rateable "taste", "price"

  before_save do
    self.vegetable.gsub!(/[\[\]\"]/, "") if attribute_present?("vegetable")
  end

end

app/models/overall_average.rb
class OverallAverage < ActiveRecord::Base
  belongs_to :rateable, :polymorphic => true
end

app/models/payment.rb
class Payment < ApplicationRecord
end

app/models/person.rb
class Person < ApplicationRecord
  validates :email, format: { with: URI::MailTo::EMAIL_REGEXP }
  validates :phone, format: { with: /\A[+-]?\d+\z/, message: "contains alphabet. Insert only number please!!!." }, length: {minimum: 8}
  validates :password, length: {minimum: 6}
end

app/models/product.rb
class Product < ApplicationRecord
  belongs_to :category
end

app/models/rate.rb
class Rate < ActiveRecord::Base
  belongs_to :rater, :class_name => "User"
  belongs_to :rateable, :polymorphic => true

  #attr_accessible :rate, :dimension

end

app/models/rating_cache.rb
class RatingCache < ActiveRecord::Base
  belongs_to :cacheable, :polymorphic => true
end

app/models/review.rb
class Review < ApplicationRecord
  mount_uploader :image, ImageUploader
end

app/models/user.rb
class User < ApplicationRecord
  ratyrate_rater
  has_many :orders
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_action :set_review, only: [:show, :edit, :update, :destroy]

  # GET /reviews
  # GET /reviews.json
  def index
    @reviews = Review.all
  end

  # GET /reviews/1
  # GET /reviews/1.json
  def show
  end

  # GET /reviews/new
  def new
    @review = Review.new
  end

  # GET /reviews/1/edit
  def edit
  end

  # POST /reviews
  # POST /reviews.json
  def create
    @review = Review.new(review_params)

    respond_to do |format|
      if @review.save
        format.html { redirect_to @review, notice: 'review was successfully created.' }
        format.json { render :show, status: :created, location: @review }
      else
        format.html { render :new }
        format.json { render json: @review.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /reviews/1
  # PATCH/PUT /reviews/1.json
  def update
    respond_to do |format|
      if @review.update(review_params)
        format.html { redirect_to @review, notice: 'review was successfully updated.' }
        format.json { render :show, status: :ok, location: @review }
      else
        format.html { render :edit }
        format.json { render json: @review.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /reviews/1
  # DELETE /reviews/1.json
  def destroy
    @review.destroy
    respond_to do |format|
      format.html { redirect_to reviews_url, notice: 'review was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_review
      @review = Review.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def review_params
      params.require(:review).permit(:comment, :rating, :image, :remove_image)
    end
end

app/helpers/aboutus_helper.rb
module AboutusHelper
end

app/helpers/charges_helper.rb
module ChargesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
  def checked(area)
    @order.vegetable.nil? ? false :  @order.vegetable.match(area)
  end
end

app/helpers/payments_helper.rb
module PaymentsHelper
end

app/helpers/people_helper.rb
module PeopleHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/reviews/_form.html.erb
<%= form_for @review, html: { multipart: true } do |f| %>
  <% if @review.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@review.errors.count, "error") %> prohibited this image from being saved:</h2>
 
      <ul>
      <% @review.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :comment %><br>
    <%= f.text_area :comment %>
  </div>

  <div class="field">
    <%= f.label :rating %><br>
    <%= f.number_field :rating %>
  </div>

  <div class="field">
    <%= f.label :image %><br>
    <%= f.file_field :image %>
    <% if f.object.image? %>
      <%= image_tag f.object.image.thumb.url %>
      <%= f.label :remove_image %>
      <%= f.check_box :remove_image %> 
    <% end %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/reviews/edit.html.erb
<h1>Editing Review</h1>

<%= render 'form', review: @review %>

<%= link_to 'Show', @review %> |
<%= link_to 'Back', reviews_path %>

app/views/reviews/index.html.erb
<html>
  <head>
    <meta charset="utf-8">
    <title> Hoagie Online Shop </title>
  </head>
  <body>
    <header>
      <section>
        <h1> Reviews </h1>
        <% if current_user %>
          <h4>Hello <%= current_user.name %>!</h4>
        <% end %>
      </section>  
      <nav>
        <ul>
          <% if current_user %>
    <li><%= link_to 'Home', root_path %></li>

    <li><%= link_to 'Products', products_path %></li>

    <li><%= link_to 'Your Orders', orders_path %></li>

    <li><%= link_to 'Change Personal Details',edit_user_registration_path %></li>

    <li><%= link_to 'Reviews', reviews_path, class: "active" %></li>

    <li><%= link_to 'About Us', aboutus_index_path %></li>

    <li><%= link_to 'Sign out', destroy_user_session_path, method: :delete %></li>

  

<% else %>
    <li><%= link_to 'Home', root_path %></li>

    <li><%= link_to 'Products', products_path %></li>

    <li><%= link_to 'Reviews', reviews_path, class: "active" %></li> 

    <li><%= link_to 'About Us', aboutus_index_path %></li> 
    
    <li><%= link_to 'Sign up', new_user_registration_path %></li>

    <li><%= link_to 'Sign in', new_user_session_path %></li>
<% end %>

        </ul>
      </nav>
      <hr>
    </header>
    <main>
      <section>
<table align="center">
  <thead>
    <tr>
      <td><b>Rating</b></td>
      <td><b>Comment</b></td>
      <td><b>Selfie</b></td>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @reviews.each do |review| %>
      <tr>
        <td><% review.rating.to_i.times do  %>
          <span class="glyphicon glyphicon-star"></span>
          <% end %>
        </td>
        <td><b>“</b><%= review.comment %><b>”</b></td>
        <td><%= image_tag review.image.thumb.url, width: 128, height: 128%></td>
        <td><%= link_to 'Show', review, class:"btn btn-primary btn-sm" %></td>
        <% if current_user && current_user.admin %>
        <td><%= link_to 'Edit', edit_review_path(review), class:"btn btn-primary btn-sm" %></td>
        <td><%= link_to 'Destroy', review, class:"btn btn-primary btn-sm", method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

<br>
<%= link_to 'New Review', new_review_path, class: "btn btn-primary btn-lg btn-block", role:"button" %>
</section>
    </main>

    <footer> 
      <h3> You will find us here: </h3>
       <div>
        <a href="https://www.facebook.com/" target="blank1"><%= image_tag("facebook", :size => "40x40") %></a>
        <a href="https://instagram.com/" target="blank2"><%= image_tag("instagram", :size => "40x40") %></a>
        <a href="https://www.twitter.com/" target="blank3"><%= image_tag("twitter", :size => "40x40") %></a>
       <div>
    </footer>
  </body> 
</html>

app/views/reviews/new.html.erb
<h1>New Review</h1>

<%= render 'form', review: @review %>

<%= link_to 'Back', reviews_path %>

app/views/reviews/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Comment:</strong>
  <%= @review.comment %>
</p>

  <%# Display full and blank stars depend on the rating value%>
<p>
  <strong>Rating:</strong>
  <% @review.rating.to_i.times do  %>
 <span class="glyphicon glyphicon-star"></span>
<% end %>
</p>

<p>
  <strong>Image:</strong>
  <%= image_tag @review.image.thumb.url%>
</p>

<% if current_user && current_user.admin %>
<%= link_to 'Edit', edit_review_path(@review) %>
<% end %>
<br>
<%= link_to 'Back', reviews_path %>